apiVersion: dev.web.api/v1alpha1
kind: FastAPIManaged
metadata:
  labels:
    app.kubernetes.io/name: fastapioperator
    app.kubernetes.io/managed-by: kustomize
  name: fastapimanaged-sample
spec:
  namespace: "demo"
  applicationImage: "fast-demo"
  apiVersion: "v21"
  replicas: 1
  ingressIP: "http://192.168.86.160.nip.io"
  gatewayClassName: "nginx"
  httpRoutePathPrefix: "/api"
  servicePort: 8000
  containerPort: 8000
